examples/auditLogging/server.js, examples/metrics/server.js, packages/apollo-voyager-audit/src/index.ts, packages/apollo-voyager-metrics/src/index.ts, packages/apollo-voyager-server/package.json, packages/apollo-voyager-server/src/apollo-voyager-server.ts, packages/apollo-voyager-server/src/voyagerResolver.ts, packages/apollo-voyager-tools/src/wrapResolvers.ts
https://issues.jboss.org/browse/AEROGEAR-8246
Changes:
- No more separate resolver wrapping for auditing and metrics
=> AEROGEAR-8246 - voyagerResolver

doc/guides/examples.md
=> doc: fix broken link in examples guide

examples/package.json, lerna.json, packages/apollo-voyager-audit/package.json, packages/apollo-voyager-context/package.json, packages/apollo-voyager-keycloak/package.json, packages/apollo-voyager-metrics/package.json, packages/apollo-voyager-server/package.json, packages/apollo-voyager-tools/package.json
=> fix: set version for all packages to 0.1.0

doc/guides/keycloak_protection.md
https://issues.jboss.org/browse/AEROGEAR-8271
As we don't have a structure for the sync docs yet, I wrote the docs here instead of writing them actually in a document in mobile docs.
This documentation can be moved to mobile docs repo later. 
Note: please don't be too picky with the formatting. I don't think it makes sense outside mobile docs repo.
=> AEROGEAR-8271 - document Keycloak protection in sync server

packages/apollo-voyager-audit/README.md, packages/apollo-voyager-audit/package.json, packages/apollo-voyager-keycloak/README.md, packages/apollo-voyager-keycloak/package.json, packages/apollo-voyager-metrics/README.md, packages/apollo-voyager-metrics/package.json, packages/apollo-voyager-server/package.json, packages/apollo-voyager-tools/README.md, packages/apollo-voyager-tools/package.json
=> doc: add basic READMEs and metadata to package.jsons

packages/apollo-voyager-audit/package.json, packages/apollo-voyager-tools/package.json
=> fix: ensure publishConfig is correct in packages

packages/apollo-voyager-keycloak/package.json, packages/apollo-voyager-metrics/package.json, packages/apollo-voyager-server/package.json
=> fix: remove files,directories properties from package.jsons

examples/package-lock.json, examples/package.json, lerna.json, package-lock.json, packages/apollo-voyager-audit/package.json, packages/apollo-voyager-keycloak/package.json, packages/apollo-voyager-metrics/package.json, packages/apollo-voyager-server/package.json, packages/apollo-voyager-tools/package.json
Bump version to 0.1.3. It is already published on NPM
=> Bump to 0.1.3

package.json
Fixes https://github.com/aerogear/apollo-voyager-server/issues/35
=> fix #35 - don't try to publish private package

examples/keycloak/.dockerignore, examples/keycloak/Dockerfile, examples/keycloak/package-lock.json, examples/keycloak/package.json, examples/keycloak/server.js
Containerise the keycloak example app as part of https://issues.jboss.org/browse/AEROGEAR-8331
=> feat: containerise the keycloak sample app

README.md, doc/api/api.md, doc/api/apollo-voyager-server.md, packages/apollo-voyager-audit/src/auditLog.ts
The aim of this PR is not to provide something complete but to add some vital information about the voyagerConfig object.
TODO in a separate PR:
* unit test for `buildSchemaDirectives`
* comments on some user facing functions.
=> doc: add the beginnings of some API docs

examples/test/conflicts.test.js
We forgot to rebase #42 on top of the latest conflicts changes so there were some minor issues. This PR resolves it!
=> fix: test for conflicts example

examples/conflicts/server.js, packages/apollo-voyager-conflicts/package.json, packages/apollo-voyager-conflicts/src/api/ConflictLogger.ts, packages/apollo-voyager-conflicts/src/api/ObjectState.ts, packages/apollo-voyager-conflicts/src/constants.ts, packages/apollo-voyager-conflicts/src/index.ts, packages/apollo-voyager-conflicts/src/states/HashObjectState.ts, packages/apollo-voyager-conflicts/src/states/VersionedObjectState.ts, packages/apollo-voyager-conflicts/test/HashObjectState.test.ts, packages/apollo-voyager-conflicts/test/VersionedObjectState.test.ts
Signed-off-by: Wojciech Trocki <wtrocki@redhat.com>
Pluggable logging :)
1. Open conflict example app
2. Trigger conflict
3. See log messages
=> feat: Enable pluggable logging

examples/package.json, lerna.json, packages/apollo-voyager-audit/package.json, packages/apollo-voyager-conflicts/package.json, packages/apollo-voyager-keycloak/package.json, packages/apollo-voyager-metrics/package.json, packages/apollo-voyager-server/package.json, packages/apollo-voyager-tools/package.json
=> feat: release 0.2.7-rc1

examples/package.json, lerna.json, packages/apollo-voyager-audit/package.json, packages/apollo-voyager-conflicts/package.json, packages/apollo-voyager-keycloak/package.json, packages/apollo-voyager-metrics/package.json, packages/apollo-voyager-server/package.json, packages/apollo-voyager-tools/package.json
=> fix: bump 0.2.7-rc2

packages/apollo-voyager-metrics/src/index.ts
Obviously, the bigger issue here is that our testing didn't catch this. With the rush to get this stuff ready for next week, I think we should solve this as part of a separate issue. https://github.com/aerogear/apollo-voyager-server/issues/58
=> fix: fix metrics middleware

.circleci/config.yml
=> fix: ensure TAG environment variable is passed to publish script

examples/package.json, lerna.json, packages/apollo-voyager-audit/package.json, packages/apollo-voyager-conflicts/package.json, packages/apollo-voyager-keycloak/package.json, packages/apollo-voyager-metrics/package.json, packages/apollo-voyager-server/package.json, packages/apollo-voyager-tools/package.json
=> fix: bump 0.2.7-rc3

scripts/publishRelease.sh
=> fix: prerelease publish

doc/api/api.md
=> doc: fix broken link

doc/guides/add_keycloak_to_openshift.md, doc/guides/keycloak_protection.md
Adding some basic instructions for how to inject keycloak config into a sync server app
=> Doc: adding notes for how to bind to keycloak

doc/guides/conflicts.md, examples/conflicts/server.js, packages/apollo-voyager-conflicts/src/api/ConflictResolution.ts, packages/apollo-voyager-conflicts/test/VersionedObjectState.test.ts
Early version for review. It is kinda hard to document this stuff in very linear fashion due to many options.
=> Docs for conflicts 

README.md, examples/README.md, examples/auditLogging/README.md, examples/auditLogging/server.js, examples/basic/README.md, examples/basic/server.js, examples/conflicts/README.md, examples/conflicts/server.js, examples/keycloak/README.md, examples/metrics/README.md, examples/metrics/server.js, examples/package.json, examples/restapi/README.md
=> Examples docs restructure

packages/apollo-voyager-tools/package.json, packages/apollo-voyager-tools/src/wrapResolvers.test.ts, packages/apollo-voyager-tools/src/wrapResolvers.ts, tslint.json
Fixes: https://issues.jboss.org/browse/AEROGEAR-8438
=> fix:add check for subscriptions when wrapping resolvers

examples/conflicts/server.js, packages/voyager-conflicts/src/api/ConflictListener.ts, packages/voyager-conflicts/src/api/ConflictLogger.ts, packages/voyager-conflicts/src/api/ObjectState.ts, packages/voyager-conflicts/src/index.ts, packages/voyager-conflicts/src/states/HashObjectState.ts, packages/voyager-conflicts/src/states/VersionedObjectState.ts, packages/voyager-conflicts/test/HashObjectState.test.ts, packages/voyager-conflicts/test/VersionedObjectState.test.ts, packages/voyager-metrics/src/api/Metrics.ts, packages/voyager-metrics/src/metrics.ts, packages/voyager-server/src/VoyagerServer.ts
@wtrocki @darahayes 
Quick impl of conflict metrics as we talked.
- Link stuff
```
npm run bootstrap
npm run compile
lerna exec -- npm link .
cd examples
npm link @aerogear/voyager-tools
npm link @aerogear/voyager-audit
npm link @aerogear/voyager-conflicts
npm link @aerogear/voyager-keycloak
npm link @aerogear/voyager-metrics
npm link @aerogear/voyager-server
```
- Run conflict example
- http://localhost:4000/graphql
- End up in conflict
- http://localhost:4000/metrics
- See conflict related metrics
I won't do any refactoring part of this PR.
=> Aerogear 8411

examples/restapi/README.md, examples/restapi/server.js
https://issues.jboss.org/browse/AEROGEAR-8460
Improved error/exception handling in the `restapi` example.
=> feat: restapi example own exception handling and throwing

examples/auditLogging/server.js, examples/conflicts/server.js, packages/voyager-audit/src/api/AuditLogger.ts, packages/voyager-audit/src/api/DefaultAuditLogger.ts, packages/voyager-audit/src/auditLog.ts, packages/voyager-conflicts/src/api/ConflictListener.ts, packages/voyager-conflicts/src/api/ObjectState.ts, packages/voyager-conflicts/src/states/HashObjectState.ts, packages/voyager-conflicts/src/states/VersionedObjectState.ts, packages/voyager-conflicts/test/HashObjectState.test.ts, packages/voyager-conflicts/test/VersionedObjectState.test.ts, packages/voyager-server/src/VoyagerServer.ts, packages/voyager-server/src/audit/AuditLogger.ts, packages/voyager-server/src/audit/DefaultAuditLogger.ts, packages/voyager-server/src/config/DefaultVoyagerConfig.test.ts, packages/voyager-server/src/context/ApolloVoyagerContextProvider.test.ts
- Link stuff
```
npm run bootstrap
npm run compile
lerna exec -- npm link .
cd examples
npm link @aerogear/voyager-tools
npm link @aerogear/voyager-audit
npm link @aerogear/voyager-conflicts
npm link @aerogear/voyager-keycloak
npm link @aerogear/voyager-metrics
npm link @aerogear/voyager-server
```
- Run conflict example
- http://localhost:4000/graphql
- End up in conflict
- See the console output
@wtrocki @darahayes 
I took the approach to make things working as we talked in our last meeting.
I won't do any refactoring part of this PR.
=> AEROGEAR-8413 Audit logs for conflicts

packages/voyager-keycloak/package.json, packages/voyager-metrics/package.json, packages/voyager-server/package.json
=> fix: bump apollo-server deps

examples/package.json, lerna.json, package.json, packages/voyager-audit/package.json, packages/voyager-conflicts/package.json, packages/voyager-keycloak/package.json, packages/voyager-metrics/package.json, packages/voyager-server/package.json, packages/voyager-tools/package.json
=> feat: release 0.4.0-rc1

examples/package.json, lerna.json, packages/voyager-audit/package.json, packages/voyager-conflicts/package.json, packages/voyager-keycloak/package.json, packages/voyager-metrics/package.json, packages/voyager-server/package.json, packages/voyager-tools/package.json
=> feat: 0.4.0-rc2

README.md
Missing info about reference app.
=> Add info for reference application

packages/voyager-keycloak/src/KeycloakSecurityService.ts, packages/voyager-keycloak/src/KeycloakToken.ts, packages/voyager-keycloak/src/schemaDirectives/hasRole.ts
add ability to manipulate tokens in the same way keycloak do. this is not ideal but they do not expose this logic by default. 
related to: 
https://github.com/aerogear/aerogear-js-sdk/pull/240
https://github.com/aerogear/ionic-showcase/pull/50
=> feat: added new methods to handle tokens

examples/package.json, lerna.json, packages/voyager-audit/package.json, packages/voyager-conflicts/package.json, packages/voyager-keycloak/package.json, packages/voyager-metrics/package.json, packages/voyager-server/package.json, packages/voyager-tools/package.json
Release build. Dropped rc as we have done already extensive amount of testing on this and prereleases are used inside showcase etc. IF we find any issues we can go with another minor or patch bumps.
=> Release 0.4.0

.circleci/config.yml, scripts/prepareRelease.sh
=> fix: release script fixes and use Node.js LTS in CI

packages/voyager-conflicts/package.json, packages/voyager-conflicts/test/HashObjectState.test.ts, packages/voyager-conflicts/test/VersionedObjectState.test.ts, packages/voyager-server/src/context/VoyagerContext.ts, packages/voyager-server/src/context/VoyagerContextConfig.ts
See individual commits for more details.
=> fix: tidy up imports and remove unused deps

renovate.json
=> fix: renovate should not pin peer dependencies

examples/keycloak/package.json, examples/package.json, lerna.json, packages/voyager-audit/package.json, packages/voyager-conflicts/package.json, packages/voyager-keycloak/package.json, packages/voyager-metrics/package.json, packages/voyager-server/package.json, packages/voyager-tools/package.json
=> feat: 0.5.0-rc1

examples/package.json, lerna.json, packages/voyager-audit/package.json, packages/voyager-conflicts/package.json, packages/voyager-keycloak/package.json, packages/voyager-metrics/package.json, packages/voyager-server/package.json, packages/voyager-tools/package.json
=> chore: 0.5.0-rc2

.circleci/config.yml
See the history in JIRA: https://issues.jboss.org/browse/AEROGEAR-8610
=> AEROGEAR-8610 sleep for some time let NPM publish be effective

examples/keycloak/package.json, examples/package.json, lerna.json, packages/voyager-audit/package.json, packages/voyager-conflicts/package.json, packages/voyager-keycloak/package.json, packages/voyager-metrics/package.json, packages/voyager-server/package.json, packages/voyager-tools/package.json
=> feat: version 0.5.0

examples/keycloak/package.json, examples/package.json, lerna.json, packages/voyager-audit/package.json, packages/voyager-conflicts/package.json, packages/voyager-keycloak/package.json, packages/voyager-metrics/package.json, packages/voyager-server/package.json, packages/voyager-tools/package.json
=> chore: 0.5.1

examples/package.json
=> fix: Add start command for examples

doc/guides/local-development.md
Docker is installed:
[terrywogan@eurovision voyager-server]$ docker -v
Docker version 18.06.0-ce, build 0ffa825
"bash: docker-compose: command not found..."
[terrywogan@eurovision voyager-server]$ docker-compose -f examples/keycloak/config/docker-compose.yml up
bash: docker-compose: command not found...
=> WIP: 'docker-compose' update to LDG

examples/package.json
Because version `0.5.1` doesn't exist for `@aerogear/voyager-subscriptions` we should use the version `0.5.2-dev.1` until the next release.
=> Fix voyager-subscriptions version in examples

packages/voyager-audit/package.json, packages/voyager-conflicts/package.json, packages/voyager-keycloak/package.json, packages/voyager-metrics/package.json, packages/voyager-server/package.json, packages/voyager-subscriptions/package.json, packages/voyager-tools/package.json
=> fix: specify ava files in package.json

package.json
=> fix: only include packages folder for coverage

examples/package.json, lerna.json, packages/voyager-audit/package.json, packages/voyager-conflicts/package.json, packages/voyager-keycloak/package.json, packages/voyager-metrics/package.json, packages/voyager-server/package.json, packages/voyager-subscriptions/package.json, packages/voyager-tools/package.json
=> fix: release 0.7.0

.circleci/config.yml, package.json, scripts/publishRelease.sh, scripts/validateRelease.sh, scripts/versionMaster.sh
https://issues.jboss.org/browse/AEROGEAR-9334
=> Release master

.github/ISSUE_TEMPLATE/1-bug-report.md, .github/ISSUE_TEMPLATE/2-feature-request.md, .github/ISSUE_TEMPLATE/3-help.md, CONTRIBUTING.md, README.md, doc/api/api.md, doc/guides/issues.md, examples/README.md, packages/voyager-audit/README.md, packages/voyager-audit/package.json, packages/voyager-conflicts/README.md, packages/voyager-keycloak/README.md, packages/voyager-keycloak/package.json, packages/voyager-metrics/README.md, packages/voyager-metrics/package.json, packages/voyager-server/README.md, packages/voyager-server/package.json, packages/voyager-subscriptions/README.md, packages/voyager-tools/README.md, packages/voyager-tools/package.json
=> chore: tidy package readmes + naming

examples/package.json, lerna.json, packages/voyager-audit/package.json, packages/voyager-conflicts/package.json, packages/voyager-keycloak/package.json, packages/voyager-metrics/package.json, packages/voyager-server/package.json, packages/voyager-subscriptions/package.json, packages/voyager-tools/package.json
=> chore: release 0.7.1

README.md
=> Docs: link fix

examples/README.md, examples/audit_logging/README.md, examples/basic/README.md, examples/conflicts/README.md, examples/keycloak/README.md, examples/metrics/README.md, examples/restapi/README.md, examples/subscriptions/README.md
=> doc: clarify prerequisites for running examples

.github/CODEOWNERS
=> remove-scoady

package.json, voyager-client/.npmrc, voyager-client/README.md, voyager-client/package.json, voyager-client/src/deleteme.test.ts, voyager-client/src/index.test.ts, voyager-client/src/index.ts, voyager-client/tsconfig.json
=> feat: initial voyager-client package

docs/integreatly/modules/ROOT/pages/conflicts-introduction.adoc, docs/integreatly/modules/ROOT/pages/data-sync-technical-overview.adoc, docs/integreatly/modules/ROOT/pages/index.adoc, docs/integreatly/modules/ROOT/pages/introducing-data-sync.adoc, docs/integreatly/modules/ROOT/pages/js-client-auth.adoc, docs/integreatly/modules/ROOT/pages/js-client-offline.adoc, docs/integreatly/modules/ROOT/pages/js-client-query.adoc, docs/integreatly/modules/ROOT/pages/realtime-intro.adoc, docs/integreatly/modules/ROOT/pages/ref_terminology.adoc, docs/integreatly/modules/ROOT/pages/server-auth-websockets.adoc, docs/integreatly/modules/ROOT/pages/server-auth.adoc, docs/integreatly/modules/ROOT/pages/server-getting-started.adoc, docs/integreatly/modules/ROOT/pages/server-mqtt-pubsub.adoc, docs/integreatly/modules/ROOT/pages/server-realtime-updates-amq.adoc
* Update links
* Correct typographical errors and ambiguous language
=> doc: update Data Sync docs

docs/integreatly/modules/ROOT/pages/ds-connect-client-to-server.adoc, docs/integreatly/modules/ROOT/pages/ds-deployment.adoc
I've added the docs but I don't really know if I need to link them up in another place to make them visible on the website. @pwright could I get some help on that?
Also, please ignore the failing build, we're still working to fix that.
=> doc: add docs for deployment and configuration

docs/integreatly/modules/ROOT/pages/data-sync-technical-overview.adoc
very difficult to test, because problem only occurs from user-docs-site repo rendering on netlify
=> remove duplicate image

docs/integreatly/modules/ROOT/pages/_partials/attributes.adoc, docs/integreatly/modules/ROOT/pages/ds-auth.adoc, docs/integreatly/modules/ROOT/pages/ds-conflict.adoc, docs/integreatly/modules/ROOT/pages/ds-debug.adoc, docs/integreatly/modules/ROOT/pages/ds-files.adoc, docs/integreatly/modules/ROOT/pages/ds-getting-started.adoc, docs/integreatly/modules/ROOT/pages/ds-introduction.adoc, docs/integreatly/modules/ROOT/pages/ds-mutation.adoc, docs/integreatly/modules/ROOT/pages/ds-offline.adoc, docs/integreatly/modules/ROOT/pages/ds-openshift.adoc, docs/integreatly/modules/ROOT/pages/ds-performance.adoc, docs/integreatly/modules/ROOT/pages/ds-query.adoc, docs/integreatly/modules/ROOT/pages/ds-realtime.adoc, docs/integreatly/modules/ROOT/pages/index.adoc, docs/integreatly/modules/ROOT/pages/master-template.adoc, docs/integreatly/modules/ROOT/pages/openshift-templates.adoc, docs/integreatly/modules/ROOT/pages/server-realtime-updates-amq.adoc
fixes to docs to allow publication downstream
=> remove tags

docs/integreatly/modules/ROOT/pages/deploying-app.adoc, docs/integreatly/modules/ROOT/pages/introducing-data-sync.adoc, docs/integreatly/modules/ROOT/pages/js-client-mutate.adoc, docs/integreatly/modules/ROOT/pages/js-client-offline.adoc, docs/integreatly/modules/ROOT/pages/js-client-query.adoc, docs/integreatly/modules/ROOT/pages/realtime-intro.adoc, docs/integreatly/modules/ROOT/pages/server-auth-websockets.adoc, docs/integreatly/modules/ROOT/pages/server-auth.adoc, docs/integreatly/modules/ROOT/pages/server-mqtt-pubsub.adoc, docs/integreatly/modules/ROOT/pages/server-realtime-updates-amq.adoc, docs/integreatly/modules/ROOT/pages/server-realtime-updates.adoc
=> INTLY-4812: Style corrections for 1.6

docs/integreatly/modules/ROOT/pages/index.adoc
=> reverting title change to ensure mobile walkthrough links work

docs/integreatly/modules/ROOT/pages/js-client-offline.adoc, docs/integreatly/modules/ROOT/pages/js-client-query.adoc, docs/integreatly/modules/ROOT/pages/js-client-realtime-updates.adoc, docs/integreatly/modules/ROOT/pages/realtime-intro.adoc, docs/integreatly/modules/ROOT/pages/server-auth-websockets.adoc, docs/integreatly/modules/ROOT/pages/server-mqtt-pubsub.adoc
=> doc: intly 4926

packages/voyager-keycloak/test/KeycloakSecurityService.test.ts, packages/voyager-keycloak/test/utils/KeycloakToken.ts
=> fix: refactor broken keycloak tests

examples/package.json, lerna.json, packages/voyager-conflicts/package.json, packages/voyager-keycloak/package.json, packages/voyager-server/package.json, packages/voyager-subscriptions/package.json, packages/voyager-tools/package.json
=> chore: release 0.8.0

docs/integreatly/modules/ROOT/pages/index.adoc
In order to support CCS standards, need to change title from App to Applications
=> update title to CCS standard

renovate.json
Fixes https://github.com/aerogear/datasync/issues/287
=> update renovate.json to fix duplicate keys issue
